spring.application.name=SpringSec
spring.security.user.name=nitin
spring.security.user.password=shastri

spring.datasource.url=jdbc:postgresql://localhost:5432/springsecurity
spring.datasource.username=postgres
spring.datasource.password=mandeshpostgresql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update